apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jinx-studios-com-tls
spec:
  secretName: jinx-studios-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jinx-studios.com
  dnsNames:
    - jinx-studios.com
    - www.jinx-studios.com